### ISSUE TITLE
Succinctly inform users of expired signed URLs

### ISSUE THREAD

**Issue by xbrianh** [xbrianh/getm#75]
Something briefer and more expressive than the following would be nice:
```
$ getm 'https://storage.googleapis.com/nih-nhlbi-biodata-catalyst-1000-genomes/CCDG_13607/Project_CCDG_13607_B01_GRM_WGS.cram.2019-02-06/Sample_HG02450/analysis/HG02450.final.cram.crai?GoogleAccessId=mbaumann1-989@dcpstage-210518.iam.gserviceaccount.com&Expires=1621889617&Signature=mFRR2BSLNSZVXB%2BJngZBdxXMp8yzyhTqZe9XafCfPeCFGo95SE%2FaY5Qn1h%2BLRogTgEkGxBCoNJBMu5YMA4BgsULnLEckF5QudlOPizB62I1chIRkL9ugVVsyBZRdSZAwMbZO6BDkzPrJz88SUzzUZvTDE82GagzEdeIWkWW5xSgcJR68sgO3QkiOBxPYMklbKtFsngsMkECmnuMndrA39Dc4B%2FWiV%2F16fPKAviMLRr3KqVoreG0g7WHgitroJGaPX6nNiPOgX567PLtST1%2FF2MehqmuVZZopB%2BSHcLl0%2BFtvXJ7tW7b3aq8C1eqHUa%2BCOlynNOPyf9d671FVHSUzYQ==&userProject=dcpstage-billing' -O ./HG02450.final.cram.crai
Traceback (most recent call last):
  File "/home/jupyter-user/notebooks/packages/bin/getm", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter-user/notebooks/packages/getm/cli.py", line 209, in main
    download(manifest, args.oneshot_concurrency, args.multipart_concurrency, args.multipart_threshold)
  File "/home/jupyter-user/notebooks/packages/getm/cli.py", line 69, in download
    if multipart_threshold >= http.size(url):
  File "/home/jupyter-user/notebooks/packages/getm/http.py", line 42, in size
    return int(self.head(url)['Content-Length'])
  File "/home/jupyter-user/notebooks/packages/getm/http.py", line 38, in head
    resp.raise_for_status()
  File "/home/jupyter-user/notebooks/packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://storage.googleapis.com/nih-nhlbi-biodata-catalyst-1000-genomes/CCDG_13607/Project_CCDG_13607_B01_GRM_WGS.cram.2019-02-06/Sample_HG02450/analysis/HG02450.final.cram.crai?GoogleAccessId=mbaumann1-989@dcpstage-210518.iam.gserviceaccount.com&Expires=1621889617&Signature=mFRR2BSLNSZVXB%2BJngZBdxXMp8yzyhTqZe9XafCfPeCFGo95SE%2FaY5Qn1h%2BLRogTgEkGxBCoNJBMu5YMA4BgsULnLEckF5QudlOPizB62I1chIRkL9ugVVsyBZRdSZAwMbZO6BDkzPrJz88SUzzUZvTDE82GagzEdeIWkWW5xSgcJR68sgO3QkiOBxPYMklbKtFsngsMkECmnuMndrA39Dc4B%2FWiV%2F16fPKAviMLRr3KqVoreG0g7WHgitroJGaPX6nNiPOgX567PLtST1%2FF2MehqmuVZZopB%2BSHcLl0%2BFtvXJ7tW7b3aq8C1eqHUa%2BCOlynNOPyf9d671FVHSUzYQ==&userProject=dcpstage-billing
```

**Comment by xbrianh** [comment]
Closed via #110
